### ISSUE TITLE
Anon-surf Connection Problem

### ISSUE THREAD

**Issue by Th3Legend11** [Und3rf10w/kali-anonsurf#35] opened 2017-06-27 18:02 UTC
Th3Legend@root: anonsurf myip 
My ip is:

curl: (6) Could not resolve host: myexternalip.com

PLEASE Help Me

**Comment by Und3rf10w** [comment] 2017-07-11 13:51
Duplicate of #18

**Closed** 2017-07-11 13:52 UTC
Labels: duplicate
