### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by nlee1131** [Und3rf10w/kali-anonsurf#31] opened 2017-06-13 22:14 UTC
~# proxychains curl 74.125.196.103 |head
ProxyChains-3.1 (http://proxychains.sf.net)
|S-chain|-<>-127.0.0.1:9050-<><>-74.125.196.103:80-<--timeout
curl: (7) Couldn't connect to server

Any help is much appreciated.

**Comment by Und3rf10w** [comment] 2017-07-11 13:55
Duplicate of #18

**Closed by Und3rf10w** 2017-07-11 13:55 UTC
Labels: duplicate
