### ISSUE TITLE
anonsurf error

### ISSUE THREAD

**Issue by rrodrigez** [Und3rf10w/kali-anonsurf#25] opened 2017-03-11 09:28 UTC
HI@ALL
i installed anonsurf on **neon KDE 5.9.3 (Kernel 4.8.0-41-generic)** by runing in Command-Line: ./installer.sh and it does not work

Error
> root@linux:/# anonsurf
> anonsurf: command not found

Then i copied the folders "**etc**" and "**usr**" from "**.../kali-anonsurf-master/kali-anonsurf-deb-src**" to "**/**" (root)
now anonsurf is working, but i have no access to the internet, need to start **i2p**. When i try to start **i2p**, i get this error popup:
> Error -- KIO Client
> Unable to create io-slave. Cannot talk to klauncher: Not connected to D-Bus server

Command-Line:
```
root@linux:/# anonsurf starti2p
 * starting I2P services
 * Modified resolvconf to use localhost and Private Internet Access DNS

Starting I2P Service...
mkdir: cannot create directory ‘/root’: Permission denied
Error creating /root/.i2p! Edit /usr/bin/i2prouter and set I2P_CONFIG_DIR
to the correct location.
Couldn't start kuiserver from org.kde.kuiserver.service: QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
klauncher not running... launching kdeinit
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 12263, result = 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
No DBUS session-bus found. Check if you have started the DBUS server.
kdeinit5: Communication error with launcher. Exiting!
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
klauncher not running... launching kdeinit
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 12268, result = 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
No DBUS session-bus found. Check if you have started the DBUS server.
kdeinit5: Communication error with launcher. Exiting!
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
klauncher not running... launching kdeinit
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 12273, result = 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
No DBUS session-bus found. Check if you have started the DBUS server.
kdeinit5: Communication error with launcher. Exiting!
klauncher not running... launching kdeinit
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/libexec/kf5/klauncher'
kdeinit5: Launched KLauncher, pid = 12278, result = 0
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
No DBUS session-bus found. Check if you have started the DBUS server.
kdeinit5: Communication error with launcher. Exiting!
kf5.kio.core: couldn't create slave: "Cannot talk to klauncher: Not connected to D-Bus server"
kf5.kio.widgets: KRun(0x13b9280) ERROR (stat): 173   "Unable to create io-slave. Cannot talk to klauncher: Not connected to D-Bus server"
```
Ther is a folder in "**.../kali-anonsurf-master/kali-anonsurf-deb-src**" named "**DEBIAN**" contains the files "**control**", "**postinst**" and "**postrm**" where to copy this files?

I installed **i2p** over the repository
```
sudo apt-add-repository ppa:i2p-maintainers/i2p
sudo apt-get update
sudo apt-get install i2p
```
no changes.

**Comment by Und3rf10w** [comment] 2017-07-11 14:06
duplicate of #26

**Closed by Und3rf10w** 2017-07-11 14:06 UTC
